catalog/urls.py
from django.conf.urls import patterns, url
from .views import CategoryDetailView, PDFTemplateView


urlpatterns = patterns('catalog.views',
    url(r'category/(?P<slug>[a-zA-Z0-9\-]+)/$', CategoryDetailView.as_view(), name='category'),
    url(r'get-price/(?P<pk>\d+)/$', PDFTemplateView.as_view(), name='price'),
)

staliurala/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

from catalog.views import HomeView


urlpatterns = patterns('catalog.views',
    url(r'^$', HomeView.as_view()),
    url(r'^catalog/', include('catalog.urls', namespace='catalog')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^summernote/', include('django_summernote.urls')),
)

if settings.DEBUG == True:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

catalog/models.py
# -*- coding: utf-8 -*-

from django.db import models
from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel
from django.core.urlresolvers import reverse


class CommonFields(TimeStampedModel):
    title = models.CharField(u'Название', max_length=500)
    description = models.TextField(u'Описание', blank=True)
    is_active = models.BooleanField(u'Активный', default=True)

    def __unicode__(self):
        return u'%s' % self.title

    class Meta:
        abstract = True


class MoveType(models.Model):
    DIRECTION_CHOICES = (
        ('double-to-left', u'Влево'),
        ('double-to-right', u'Вправо'),
        ('double-to-top', u'Вверх'),
        ('double-to-bottom', u'Вниз'),
    )
    type = models.CharField(max_length=16, choices=DIRECTION_CHOICES)

    def __unicode__(self):
        return u'%s' % filter(lambda x: x[0] == self.type, self.DIRECTION_CHOICES)[0][1]


class CategoryBlock(CommonFields):
    FORM_CHOICES = (
        ('simple', u'Обычный'),
        ('double-width', u'Двойная ширина'),
        ('double-height', u'Двойная высота'),
    )

    image = models.ImageField(u'Картинка', upload_to='catalog/blocks/')
    form_type = models.CharField(u'Форма блока', max_length=13, choices=FORM_CHOICES, default='simple')
    move_type = models.ManyToManyField(MoveType)

    class Meta():
        verbose_name = u'Блок'
        verbose_name_plural = u'Блоки'


class Category(CommonFields):
    block = models.ForeignKey(CategoryBlock, verbose_name=u'Блок', related_name='categories')
    image = models.ImageField(u'Картинка', upload_to='catalog/category/', blank=True)
    slug = AutoSlugField(populate_from='title')

    seo_title = models.CharField('Title', max_length=80, blank=True)
    seo_keywords = models.CharField('Keywords', max_length=250, blank=True)
    seo_description = models.CharField('Description', max_length=200, blank=True)

    def get_absolute_url(self):
        return reverse('catalog:category', args=[self.slug])

    class Meta():
        verbose_name = u'Категория'
        verbose_name_plural = u'Категории'


class Price(CommonFields):
    category = models.ForeignKey(Category, related_name='prices')
    url = models.CharField('URL', max_length=500)

    class Meta():
        verbose_name = u'Прайс'
        verbose_name_plural = u'Прайсы'

partners/models.py
# -*- coding: utf-8 -*-

from django.db import models


class Partner(models.Model):
    title = models.CharField(u'Название', max_length=500)
    logo = models.ImageField(u'Логотип', upload_to='partners')
    description = models.TextField(u'Описание', blank=True)
    url = models.URLField(u'Ссылка на сайт', blank=True)

    class Meta:
        verbose_name = u'Партнер'
        verbose_name_plural = u'Партнеры'

site_settings/models.py
# -*- coding: utf-8 -*-

from django.db import models


class SiteSetting(models.Model):
    about_us = models.TextField(u'О компании', blank=True)
    address = models.CharField(u'Адресс', max_length=2000, blank=True)

    def __unicode__(self):
        return u'Настройки сайта'

    class Meta:
        verbose_name = u'Настройки сайта'
        verbose_name_plural = u'Настройки сайта'

class Phone(models.Model):
    number = models.CharField(max_length=30)
    site = models.ForeignKey(SiteSetting)

    class Meta:
        abstract = True


class HeaderPhone(Phone):
    pass


class ManagerPhone(Phone):
    pass


class LogisticPhone(Phone):
    pass

catalog/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm, ModelMultipleChoiceField, CheckboxSelectMultiple
from .models import CategoryBlock, MoveType, Category
from .validators import validate_move_types
from django.utils.safestring import mark_safe
from django.contrib.admin.widgets import AdminFileWidget


class AdminFileWidgetWithPreview(AdminFileWidget):

    def render(self, name, value, attrs=None):
        output = []
        if value and hasattr(value, "url"):
            output.append(('<p><img src="%s"/></p>' % value.url))

        output.append(super(AdminFileWidgetWithPreview, self).render(name, value, attrs))
        return mark_safe(u''.join(output))


class CategoryBlockAdminForm(ModelForm):
    move_type = ModelMultipleChoiceField(
        label=u'Анимация блока',
        widget = CheckboxSelectMultiple,
        queryset=MoveType.objects.all(),
        validators=[validate_move_types],
    )

    class Meta:
        model = CategoryBlock
        widgets = {
            'image': AdminFileWidgetWithPreview(),
        }

    class Media:
        css = {
            'all': ('admin/admin.checkbox.inline.css',)
        }


class CategoryAdminForm(ModelForm):
    class Meta:
        model = Category
        widgets = {
            'image': AdminFileWidgetWithPreview(),
        }

catalog/views.py
# -*- coding: utf-8 -*-

from .models import CategoryBlock, Category, Price
from django.views.generic import TemplateView, DetailView
# from easy_pdf.views import PDFTemplateView
from tools.parser import Parser


class HomeView(TemplateView):
    template_name = 'catalog/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['block_list'] = CategoryBlock.objects.filter(is_active=True).prefetch_related('categories')
        return context


class CategoryDetailView(DetailView):
    template_name = 'catalog/category.html'
    model = Category



from django.http import HttpResponse, Http404
from xhtml2pdf import pisa


class PDFTemplateView(TemplateView):
    template_name = 'price_template.html'
    pdf_file_name = ''

    def get_context_data(self, **kwargs):
        context = super(PDFTemplateView, self).get_context_data(**kwargs)
        context['title'] = self.price_obj.title
        context['table'] = str(self.get_table())
        return context

    def render_to_response(self, context, **response_kwargs):
        template_response = super(PDFTemplateView, self).render_to_response(context, **response_kwargs)
        html = str(template_response.render())

        response = HttpResponse(mimetype='application/pdf')
        # response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="%s"' % self.pdf_file_name
        response['Content-Type'] = 'application/pdf'

        try:
            pisaStatus = pisa.CreatePDF(
                src = html,
                dest=response,
                encoding='utf-8',
            )
        except:
            raise Http404

        return response

    def get_table(self):
        p = Parser()
        return p.get_table(self.price_obj.url)

    def set_file_name(self):
        self.pdf_file_name = u'price-%s.pdf' % self.price_obj.pk


    def get(self, request, *args, **kwargs):
        self.price_obj = Price.objects.get(pk=kwargs['pk'])
        self.set_file_name()
        return super(PDFTemplateView, self).get(request, *args, **kwargs)

catalog/templates/catalog/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block page_css %}{% endblock %}
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<body>
    {% block content %}{% endblock %}
    {% block page_js %}{% endblock %}
</body>
</html>

catalog/templates/catalog/category.html
{% extends 'catalog/base.html' %}

{% block page_css %}
{#    <link rel="stylesheet" href="{{ STATIC_URL }}catalog/css/home.css"/>#}
{% endblock %}

{% block page_js %}
{#    <script src="{{ STATIC_URL }}catalog/js/home.js"></script>#}
{% endblock %}

{% block content %}
    <h1>Category page</h1>
    <h2>{{ category.title }}</h2>

    <h4>Прайсы</h4>
    <ul>
        {% for price in category.prices.all %}
            <a href="{% url 'catalog:price' price.pk %}">{{ price.title }}</a>
        {% endfor %}
    </ul>

{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block page_css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}catalog/css/home.css"/>
{% endblock %}

{% block page_js %}
    <script src="{{ STATIC_URL }}catalog/js/home.js"></script>
{% endblock %}

{% block content %}
    <h1>Home page</h1>
    <h2></h2>
    <ul>
        {% for block in block_list %}
            <li>
                {{ block.title }}
                <ul>
                    {% for category in block.categories.all %}
                        <li><a href="{{ category.get_absolute_url }}">{{ category.title }}</a></li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

catalog/templates/easy_pdf.html
{% extends 'base.html' %}

{% block content %}
    <div id="content">
        <h1>Hi there!</h1>
    </div>
{% endblock %}

catalog/templates/price_template.html
{% load price_template_tags %}
<html>
<head lang="ru">
    <title>Dudud</title>
    <style>
        @font-face {
            font-family: DejaMono;
            src: url('{% get_font_path %}');
        }
        * {
            font-family: DejaMono !important;
        }
        table {
            border-collapse: collapse;
            border: 1px solid black;
        }
        th, td {
            padding: 3px 5px 0;
            text-align: center;
            border: 1px solid black;
        }
    </style>
</head>
<body>
    <h4>{{ title }}</h4>
    {{ table|safe }}
</body>
</html>

staliurala/templates/admin-tools/site-content.html
{% load i18n %}
{% if not module.is_empty %}
    <div id="module_{{ module.id }}" class="{{ module.render_css_classes }}" xmlns="http://www.w3.org/1999/html">
        {% if module.show_title and module.title %}<h2>{% if module.title_url %}<a href="{{ module.title_url }}">{% trans module.title %}</a>{% else %}{% trans module.title %}{% endif %}</h2>{% endif %}
        <div class="dashboard-module-content">
            {% spaceless %}
                <ul class="site-content">
                    <li>
                        <div style="float: left;">
                            <a href="/admin/partners/partner/"><img  src="/static/admin-tools/img/partners.png"/></a>
                            <a href="/admin/partners/partner/">Партнеры</a>
                        </div>
                    </li>
                    <li>
                        <div style="float: left;">
                            <a href="/admin/catalog/categoryblock/"><img  src="/static/admin-tools/img/blocks.png"/></a>
                            <a href="/admin/catalog/categoryblock/">Блоки на главной</a>
                        </div>
                    </li>
                    <li>
                        <div style="float: left;">
                            <a href="/admin/catalog/category/"><img  src="/static/admin-tools/img/categories.png"/></a>
                            <a href="/admin/catalog/category/">Категории</a>
                        </div>
                    </li>
                    <li>
                        <div style="float: left;">
                            <a href="/admin/catalog/price/"><img  src="/static/admin-tools/img/prices.png"/></a>
                            <a href="/admin/catalog/price/">Прайсы</a>
                        </div>
                    </li>
                </ul>
            {% endspaceless %}
        </div>
    </div>
{% endif %}

staliurala/templates/admin-tools/site-settings.html
{% load i18n %}
{% if not module.is_empty %}
    <div id="module_{{ module.id }}" class="{{ module.render_css_classes }}" xmlns="http://www.w3.org/1999/html">
        {% if module.show_title and module.title %}<h2>{% if module.title_url %}<a href="{{ module.title_url }}">{% trans module.title %}</a>{% else %}{% trans module.title %}{% endif %}</h2>{% endif %}
        <div class="dashboard-module-content">
            {% spaceless %}
                <ul class="site-settings">
                    <li>
                        <div style="float: left;">
                            <a href="/admin/site_settings/sitesetting/1/"><img  src="/static/admin-tools/img/settings.png"/></a>
                            <a href="/admin/site_settings/sitesetting/1/">Настройки сайта</a>
                        </div>
                    </li>
                </ul>
            {% endspaceless %}
        </div>
    </div>
{% endif %}